In [1]:
import pandas as pd

moms = pd.read_csv('moms.csv', usecols=['edad', 'ascendencia',
       'estado_laboral', 'sueldo', 'busca_otro_trabajo', 'actividad',
       'asistencia alguna vez a enseñanza', 'edu preescolar', 'edu primaria',
       'edu media', 'edu técnica', 'edu univ o simil', 'edu terciario no uni',
       'edu posgrado', 'edu mag prof', 'hijos'])

moms['estado_laboral'] = moms['estado_laboral'].astype('category').cat.codes
moms['actividad'] = moms['actividad'].astype('category').cat.codes

moms.columns

Index(['edad', 'ascendencia', 'estado_laboral', 'sueldo', 'busca_otro_trabajo',
       'actividad', 'asistencia alguna vez a enseñanza', 'edu preescolar',
       'edu primaria', 'edu media', 'edu técnica', 'edu univ o simil',
       'edu terciario no uni', 'edu posgrado', 'edu mag prof', 'hijos'],
      dtype='object')

In [3]:
# Dummies para modelo
 
moms = pd.get_dummies(moms, drop_first=True)

moms

,edad,estado_laboral,sueldo,actividad,hijos,ascendencia_Asiática o amarilla,ascendencia_Blanca,ascendencia_Indígena,busca_otro_trabajo_Sí,asistencia alguna vez a enseñanza_Sí,...,edu terciario no uni_Asiste actualmente,edu terciario no uni_No asistió,"edu terciario no uni_Sí, asistió",edu posgrado_Asiste actualmente,edu posgrado_No asistió,edu posgrado_Sin dato,"edu posgrado_Sí, asistió",edu mag prof_Asiste actualmente,edu mag prof_No asistió,"edu mag prof_Sí, asistió"
0,34.0,0,20000.0,99,1,1,0,0,1,1,...,0,0,0,0,0,0,0,0,0,0
1,34.0,0,19000.0,99,1,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
2,52.0,0,45000.0,244,1,0,1,0,0,1,...,0,1,0,0,0,0,0,0,1,0
3,42.0,0,18500.0,231,2,0,1,0,0,1,...,0,1,0,0,0,0,0,0,1,0
4,52.0,0,50000.0,244,1,0,1,0,0,1,...,0,1,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10082,43.0,0,22500.0,42,0,0,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
10083,43.0,0,23000.0,42,0,0,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
10084,34.0,0,22000.0,159,0,0,1,0,0,1,...,0,1,0,1,0,0,0,0,1,0
10085,34.0,0,30000.0,159,0,0,1,0,0,1,...,0,1,0,1,0,0,0,0,1,0
10086,34.0,0,30000.0,159,0,0,1,0,0,1,...,0,1,0,1,0,0,0,0,1,0

In [4]:
# Feautures
X = moms.drop('hijos', axis=1)

# Target
y = moms['hijos']

In [5]:
# Split #30% test, 70% para train
from sklearn.model_selection import train_test_split 

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=42)

In [6]:
# Create model
 
from sklearn.tree import DecisionTreeClassifier 
tree = DecisionTreeClassifier(max_depth=2, random_state = 42)

In [7]:
# Train model
tree.fit(X_train,y_train)

DecisionTreeClassifier(max_depth=2, random_state=42)

In [8]:
# Exportar el modelo
import joblib
joblib.dump(tree,'tree.pkl')

['tree.pkl']

In [9]:
modelo = joblib.load('tree.pkl')

In [10]:
# Predicciones
 
y_train_pred = tree.predict(X_train)
y_test_pred = tree.predict(X_test)

In [11]:
# Accuracy score

from sklearn.metrics import accuracy_score

train_accuracy = accuracy_score(y_train, y_train_pred)
test_accuracy = accuracy_score(y_test, y_test_pred)

print('Train accuracy', train_accuracy)
print('Test accuracy',test_accuracy)

Train accuracy 0.44575070821529744
Test accuracy 0.4317806408985794

## El bajo acurracy de los datos puede significar que la información con la que cuenta nuestro dataset no es la ideal.